server:
  port: ${PORT:9999}

spring:
  application:
    name: dh-cuenta-service

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: info,health

  info:
    env:
      enabled: true

info:
  app:
    name: dh-cuenta-service
    description: Servicio probando Eureka
    version: 1.0.0
