server:
  port: ${PORT:${SERVER_PORT:0}}

spring:
  application:
    name: serie-service
  mongodb:
    embedded:
      version: 4.0.2
  data:
    mongodb:
      database: movie-db
      port: 27018
  zipkin:
    base-url: http://localhost:9411/
    enabled: true
  rabbitmq:
    username: guest
    password: guest
    host: localhost
    port: 5672

info:
  application:
    name: ${spring.application.name}
    description: Serie Service for Movies Application
    version: 1.0.0

management:
  endpoints:
    web:
      exposure:
        include: info, health
  info:
    env:
      enabled: true

eureka:
  instance:
    hostname: localhost
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

